In [1]:
content = '''AmbTrs C CT N3 H 0 180 0 0 0.00 25.63 0.00 0. 6.0
AmbTrs CT C OH HO 0 180 0 0 0.00 9691.61 0.00 0. 2.0
AmbTrs HC CT N3 H 0 0 0 0 0.00 16.93 0.00 0. 6.0
AmbTrs O2 C CT HC 0 0 0 0 0.00 14.50 0.00 0. 6.0
AmbTrs O2 C CT N3 0 0 0 0 0.00 14.50 0.00 0. 6.0
AmbTrs O2 C OH HO 0 0 0 0 0.00 18335.01 0.00 0. 2.0
AmbTrs OH C CT HC 0 0 0 0 0.00 14.50 0.00 0. 6.0
AmbTrs OH C CT N3 0 0 0 0 0.00 14.50 0.00 0. 6.0'''
content_list = content.split('\n')

# Split each item of the list into a sublist based on space delimiter
split_content = [item.split() for item in content_list]
[print(i) for i in split_content]

['AmbTrs', 'C', 'CT', 'N3', 'H', '0', '180', '0', '0', '0.00', '25.63', '0.00', '0.', '6.0']
['AmbTrs', 'CT', 'C', 'OH', 'HO', '0', '180', '0', '0', '0.00', '9691.61', '0.00', '0.', '2.0']
['AmbTrs', 'HC', 'CT', 'N3', 'H', '0', '0', '0', '0', '0.00', '16.93', '0.00', '0.', '6.0']
['AmbTrs', 'O2', 'C', 'CT', 'HC', '0', '0', '0', '0', '0.00', '14.50', '0.00', '0.', '6.0']
['AmbTrs', 'O2', 'C', 'CT', 'N3', '0', '0', '0', '0', '0.00', '14.50', '0.00', '0.', '6.0']
['AmbTrs', 'O2', 'C', 'OH', 'HO', '0', '0', '0', '0', '0.00', '18335.01', '0.00', '0.', '2.0']
['AmbTrs', 'OH', 'C', 'CT', 'HC', '0', '0', '0', '0', '0.00', '14.50', '0.00', '0.', '6.0']
['AmbTrs', 'OH', 'C', 'CT', 'N3', '0', '0', '0', '0', '0.00', '14.50', '0.00', '0.', '6.0']


[None, None, None, None, None, None, None, None]

In [13]:
replace_list = ['C CT N3 H', 'HC CT N3 H', 'OH C CT HC', 'O2 C OH HO', 'CT C OH HO', 'OH C CT N3']
rep_sublist = [ i.split(' ') for i in replace_list]
rep_sublist, replace_list

([['C', 'CT', 'N3', 'H'],
  ['HC', 'CT', 'N3', 'H'],
  ['OH', 'C', 'CT', 'HC'],
  ['O2', 'C', 'OH', 'HO'],
  ['CT', 'C', 'OH', 'HO'],
  ['OH', 'C', 'CT', 'N3']],
 ['C CT N3 H',
  'HC CT N3 H',
  'OH C CT HC',
  'O2 C OH HO',
  'CT C OH HO',
  'OH C CT N3'])

In [3]:
import numpy as np

for idx, line in enumerate(split_content):
    arr_tmp = np.asarray(split_content[idx][9:13])
    arr_float = arr_tmp.astype(float)
    # Replace elements different from 0.0 with 1.0
    arr_float[arr_float != 0.0] = 1.0
    print(arr_float)

[0. 1. 0. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]
[0. 1. 0. 0.]


In [14]:
tors_list =[]
for idx, replace_item in enumerate(rep_sublist):
    for line_idx, line in enumerate(split_content):
        if line[1:5] == replace_item:
           # print(line[1:5], replace_item, split_content[idx][9:13]) 
            arr_tmp = np.asarray(split_content[idx][9:13])
            arr_float = arr_tmp.astype(float)
            ## Replace elements different from 0.0 with 1.0
            arr_float[arr_float != 0.0] = 1.0
            print(line[1:5], replace_item, arr_float, split_content[line_idx][9:13])
            str_type = arr_float.astype(str)
            
           # Replace the line with your desired replacement string or line
            split_content[line_idx][9:13] = list(str_type)
            break

[print(i) for i in split_content]
#updated_content = ' '.join(split_content)
#print(updated_content)

['C', 'CT', 'N3', 'H'] ['C', 'CT', 'N3', 'H'] [0. 1. 0. 0.] ['0.0', '1.0', '0.0', '0.0']
['HC', 'CT', 'N3', 'H'] ['HC', 'CT', 'N3', 'H'] [0. 1. 0. 0.] ['0.0', '1.0', '0.0', '0.0']
['OH', 'C', 'CT', 'HC'] ['OH', 'C', 'CT', 'HC'] [0. 1. 0. 0.] ['0.0', '1.0', '0.0', '0.0']
['O2', 'C', 'OH', 'HO'] ['O2', 'C', 'OH', 'HO'] [0. 1. 0. 0.] ['0.0', '1.0', '0.0', '0.0']
['CT', 'C', 'OH', 'HO'] ['CT', 'C', 'OH', 'HO'] [0. 1. 0. 0.] ['0.0', '1.0', '0.0', '0.0']
['OH', 'C', 'CT', 'N3'] ['OH', 'C', 'CT', 'N3'] [0. 1. 0. 0.] ['0.0', '1.0', '0.0', '0.0']
['AmbTrs', 'C', 'CT', 'N3', 'H', '0', '180', '0', '0', '0.0', '1.0', '0.0', '0.0', '6.0']
['AmbTrs', 'CT', 'C', 'OH', 'HO', '0', '180', '0', '0', '0.0', '1.0', '0.0', '0.0', '2.0']
['AmbTrs', 'HC', 'CT', 'N3', 'H', '0', '0', '0', '0', '0.0', '1.0', '0.0', '0.0', '6.0']
['AmbTrs', 'O2', 'C', 'CT', 'HC', '0', '0', '0', '0', '0.00', '14.50', '0.00', '0.', '6.0']
['AmbTrs', 'O2', 'C', 'CT', 'N3', '0', '0', '0', '0', '0.00', '14.50', '0.00', '0.', '6.0']
['

[None, None, None, None, None, None, None, None]